version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    build: .
    command: uvicorn main:app  --port 8080 --reload
    volumes:
      - .:/app
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - redis
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
